/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.superrent.gui;

import com.sun.org.apache.xalan.internal.xsltc.compiler.util.StringStack;
import com.superrent.DataBase.ConnectDB;
import com.superrent.modules.Encrypt;
import com.superrent.modules.CommonFunc;
import com.superrent.modules.ManageFleet;
import com.superrent.modules.Rent;
import com.superrent.modules.Reserve;
import com.superrent.modules.Return;
import java.awt.event.ActionEvent;

import java.io.IOException;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListModel;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Iniyan
 */
public class SuperRent extends javax.swing.JFrame {

    /**
     * Creates new form SuperRent
     */
    public SuperRent() throws ClassNotFoundException, SQLException, IOException {
        initComponents();

        //initReserve();

        //initRent();
        initReturn();
        //initReserve();
        initManageFleet();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleGroupRadio = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        loginpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pwdField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        modulepane = new javax.swing.JPanel();
        moduletab = new javax.swing.JTabbedPane();
        RentVehicles = new javax.swing.JPanel();
        cusNumLbl = new javax.swing.JLabel();
        cusNumField = new javax.swing.JTextField();
        dlNumLbl = new javax.swing.JLabel();
        dlNumField = new javax.swing.JTextField();
        ccNumField = new javax.swing.JTextField();
        ccNumLbl = new javax.swing.JLabel();
        expDateLbl = new javax.swing.JLabel();
        expDateCh = new com.toedter.calendar.JDateChooser();
        cardTypeLbl = new javax.swing.JLabel();
        cardTypeCombo = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        reserveVehicles = new javax.swing.JPanel();
        brnchIdLbl = new javax.swing.JLabel();
        brnchIdCombo = new javax.swing.JComboBox();
        pickupDt = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        pickupHour = new javax.swing.JSpinner(modelPickHH);
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pickupMin = new javax.swing.JSpinner(modelPickMM);
        jLabel8 = new javax.swing.JLabel();
        vehicleCatCombo = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        vehicleTypeCombo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        unreservedVehiTable = new javax.swing.JTable();
        searchBtn = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        rentBtn = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        dropOffDate = new com.toedter.calendar.JDateChooser();
        jLabel44 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dropoffHHSpin = new javax.swing.JSpinner(modelDropHH);
        dropoffMMSpin = new javax.swing.JSpinner(modelDropMM);
        jScrollPane4 = new javax.swing.JScrollPane();
        equipmentsList = new javax.swing.JList();
        addEquipBtn = new javax.swing.JButton();
        removeEquipBtn = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        selectedList = new javax.swing.JList();
        searchEqupBtn = new javax.swing.JButton();
        returnVehicles = new javax.swing.JPanel();
        ReturnCustomerPnobeNum_jLabel9 = new javax.swing.JLabel();
        ReturnVin_jTextField8 = new javax.swing.JTextField();
        ReturnDate_jLabel19 = new javax.swing.JLabel();
        ReturnDate_jDateChooser3 = new com.toedter.calendar.JDateChooser();
        ReturnTime_jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        ReturnOdoRead_jLabel23 = new javax.swing.JLabel();
        ReturnOdometer_jTextField9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        ReturnRoadStar_jCheckBox2 = new javax.swing.JCheckBox();
        ReturnCalculate_jButton6 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ReturnCheckOverDueDis_jTable2 = new javax.swing.JTable();
        ReturnCheck_jButton2 = new javax.swing.JButton();
        ReturnFuelReading_jTextField2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        ReturnCheckOverDue_jButton2 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        ReturnDisplay_jTable2 = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        ReturnDisplayFee_jTable2 = new javax.swing.JTable();
        ReturnRedeem_jCheckBox1 = new javax.swing.JCheckBox();
        ReturnTimeHH_jSpinner1 = new javax.swing.JSpinner();
        ReturnTimeMM_jSpinner1 = new javax.swing.JSpinner();
        jLabel16 = new javax.swing.JLabel();
        ReturnPay_jButton2 = new javax.swing.JButton();
        ReturnCreditCard_jTextField1 = new javax.swing.JTextField();
        ReturnCash_jTextField2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        manageCustomer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        cusFristNameField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        cusLastNameField = new javax.swing.JTextField();
        streetAddField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton9 = new javax.swing.JButton();
        manageFleet = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        cartypeCombo = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        manufacturerCombo = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        nameCombo = new javax.swing.JComboBox();
        addBtn = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        branchCombo = new javax.swing.JComboBox();
        jPanel4 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        userNamepanel = new javax.swing.JPanel();
        firstnameLbl = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameLbl = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        userNameLbl = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        emailIdLbl = new javax.swing.JLabel();
        emailIdField = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        managerRadio = new javax.swing.JRadioButton();
        clerkRadio = new javax.swing.JRadioButton();
        addEmployeeBtn = new javax.swing.JButton();
        branchIdCombo = new javax.swing.JComboBox();
        branchIdLbl = new javax.swing.JLabel();
        roleLbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginpanel.setPreferredSize(new java.awt.Dimension(890, 810));
        loginpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User Name :");
        loginpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));
        loginpanel.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 220, -1));

        jLabel2.setText("Password   :");
        loginpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));
        loginpanel.add(pwdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 220, -1));

        jButton1.setText("Employee Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        loginpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 160, -1));
        loginpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 340, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Super Rent Login Page");
        loginpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 440, 70));

        modulepane.setPreferredSize(new java.awt.Dimension(1380, 810));
        modulepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        moduletab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moduletabMouseClicked(evt);
            }
        });

        RentVehicles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cusNumLbl.setText("Customer Phone Number* :");
        RentVehicles.add(cusNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        RentVehicles.add(cusNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 130, -1));

        dlNumLbl.setText("Driver License*  :");
        RentVehicles.add(dlNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));
        RentVehicles.add(dlNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 160, -1));
        RentVehicles.add(ccNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 130, -1));

        ccNumLbl.setText("Credit Card Number*        :");
        RentVehicles.add(ccNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        expDateLbl.setText("Expiry Date*      :");
        RentVehicles.add(expDateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));
        RentVehicles.add(expDateCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 160, -1));

        cardTypeLbl.setText("Card type*  :");
        RentVehicles.add(cardTypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        cardTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "American Express", "MasterCard", "Visa" }));
        RentVehicles.add(cardTypeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 150, -1));

        jButton5.setText("Auto Fill");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        RentVehicles.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 130, -1));
        RentVehicles.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, -1));

        jLabel14.setText("Confirmation Number         :");
        RentVehicles.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        moduletab.addTab("Rent", RentVehicles);

        reserveVehicles.setMinimumSize(new java.awt.Dimension(1000, 615));
        reserveVehicles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brnchIdLbl.setText("Branch ID*                       :");
        reserveVehicles.add(brnchIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        brnchIdCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        brnchIdCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                brnchIdComboItemStateChanged(evt);
            }
        });
        reserveVehicles.add(brnchIdCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 80, -1));
        reserveVehicles.add(pickupDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 140, -1));

        jLabel3.setText("Pickup Date*                    :");
        reserveVehicles.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, -1, -1));
        reserveVehicles.add(pickupHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 90, 40, -1));

        jLabel6.setText("Pickup Time :");
        reserveVehicles.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, -1, -1));

        jLabel7.setText("HH");
        reserveVehicles.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 90, -1, -1));
        reserveVehicles.add(pickupMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 90, 40, -1));

        jLabel8.setText("MM");
        reserveVehicles.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 90, -1, -1));

        vehicleCatCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Select" }));
        vehicleCatCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vehicleCatComboActionPerformed(evt);
            }
        });
        reserveVehicles.add(vehicleCatCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 220, -1));

        jLabel10.setText("Vehicle Type                    :");
        reserveVehicles.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 160, -1));

        vehicleTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "CAR", "TRUCK" }));
        vehicleTypeCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vehicleTypeComboItemStateChanged(evt);
            }
        });
        reserveVehicles.add(vehicleTypeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 210, 220, -1));

        unreservedVehiTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vehicle ID", "Make", "Vehicle Type", "Colour", "Doors"
            }
        ));
        jScrollPane1.setViewportView(unreservedVehiTable);

        reserveVehicles.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 550, 1290, 160));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        reserveVehicles.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 500, -1, -1));

        resetBtn.setText("Reset");
        resetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetBtnActionPerformed(evt);
            }
        });
        reserveVehicles.add(resetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, -1, -1));

        rentBtn.setText("Rent");
        rentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rentBtnActionPerformed(evt);
            }
        });
        reserveVehicles.add(rentBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 720, -1, -1));

        jLabel13.setText("Vehicle Category*             :");
        reserveVehicles.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));

        jLabel43.setText("Dropoff*                          :");
        reserveVehicles.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        reserveVehicles.add(dropOffDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 140, -1));

        jLabel44.setText("Dropoff Time :");
        reserveVehicles.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 150, -1, -1));

        jLabel5.setText("HH");
        reserveVehicles.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 150, -1, -1));

        jLabel12.setText("MM");
        reserveVehicles.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, -1, -1));
        reserveVehicles.add(dropoffHHSpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, 40, -1));
        reserveVehicles.add(dropoffMMSpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 40, -1));

        jScrollPane4.setViewportView(equipmentsList);

        reserveVehicles.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 190, 100));

        addEquipBtn.setText(">>");
        addEquipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEquipBtnActionPerformed(evt);
            }
        });
        reserveVehicles.add(addEquipBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, -1, -1));

        removeEquipBtn.setText("<<");
        removeEquipBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEquipBtnActionPerformed(evt);
            }
        });
        reserveVehicles.add(removeEquipBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, -1, -1));

        jScrollPane5.setViewportView(selectedList);

        reserveVehicles.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 360, 180, 100));

        searchEqupBtn.setText("Search Equipments");
        searchEqupBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEqupBtnActionPerformed(evt);
            }
        });
        reserveVehicles.add(searchEqupBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 320, 180, -1));

        moduletab.addTab("Reserve", reserveVehicles);

        ReturnCustomerPnobeNum_jLabel9.setText("Vin* :");

        ReturnVin_jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnVin_jTextField8ActionPerformed(evt);
            }
        });

        ReturnDate_jLabel19.setText("Return Date* :");

        ReturnTime_jLabel20.setText("Return Time* :");

        jLabel21.setText("HH");

        ReturnOdoRead_jLabel23.setText("Current Odometer Reading* :");

        jLabel24.setText("KM");

        ReturnRoadStar_jCheckBox2.setText("Road Star");
        ReturnRoadStar_jCheckBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnRoadStar_jCheckBox2ActionPerformed(evt);
            }
        });

        ReturnCalculate_jButton6.setText("Calculate");
        ReturnCalculate_jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnCalculate_jButton6ActionPerformed(evt);
            }
        });

        ReturnCheckOverDueDis_jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Confirmation No", "Customer ID", "Phone", "Branch ID", "Expected Time", "Vin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ReturnCheckOverDueDis_jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReturnCheckOverDueDis_jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ReturnCheckOverDueDis_jTable2);

        ReturnCheck_jButton2.setText("Check");
        ReturnCheck_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnCheck_jButton2ActionPerformed(evt);
            }
        });

        ReturnFuelReading_jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnFuelReading_jTextField2ActionPerformed(evt);
            }
        });

        jLabel9.setText("Fuel Reading* :");

        ReturnCheckOverDue_jButton2.setText("Check Over Due");
        ReturnCheckOverDue_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnCheckOverDue_jButton2ActionPerformed(evt);
            }
        });

        ReturnDisplay_jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Confirmation No", "First Name", "Last Name", "Vin", "Status"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(ReturnDisplay_jTable2);

        ReturnDisplayFee_jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Entry", "Detail", "Cost"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(ReturnDisplayFee_jTable2);

        ReturnRedeem_jCheckBox1.setText("Reedem");
        ReturnRedeem_jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnRedeem_jCheckBox1ActionPerformed(evt);
            }
        });

        jLabel16.setText("MM");

        ReturnPay_jButton2.setText("Pay");
        ReturnPay_jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnPay_jButton2ActionPerformed(evt);
            }
        });

        ReturnCreditCard_jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnCreditCard_jTextField1ActionPerformed(evt);
            }
        });

        jLabel11.setText("Credit Card:");

        jLabel17.setText("Cash:");

        javax.swing.GroupLayout returnVehiclesLayout = new javax.swing.GroupLayout(returnVehicles);
        returnVehicles.setLayout(returnVehiclesLayout);
        returnVehiclesLayout.setHorizontalGroup(
            returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnVehiclesLayout.createSequentialGroup()
                .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnVehiclesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(ReturnCheckOverDue_jButton2))
                    .addGroup(returnVehiclesLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returnVehiclesLayout.createSequentialGroup()
                                .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(ReturnDate_jLabel19)
                                    .addComponent(ReturnTime_jLabel20)
                                    .addComponent(ReturnOdoRead_jLabel23)
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ReturnFuelReading_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ReturnRoadStar_jCheckBox2)
                                    .addComponent(ReturnRedeem_jCheckBox1)
                                    .addGroup(returnVehiclesLayout.createSequentialGroup()
                                        .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ReturnOdometer_jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(returnVehiclesLayout.createSequentialGroup()
                                                .addComponent(ReturnTimeHH_jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jLabel21)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(returnVehiclesLayout.createSequentialGroup()
                                                .addComponent(ReturnTimeMM_jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(3, 3, 3)
                                                .addComponent(jLabel16))
                                            .addComponent(jLabel24)))))
                            .addGroup(returnVehiclesLayout.createSequentialGroup()
                                .addGap(188, 188, 188)
                                .addComponent(ReturnDate_jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(returnVehiclesLayout.createSequentialGroup()
                                .addComponent(ReturnCustomerPnobeNum_jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ReturnVin_jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ReturnCheck_jButton2)))))
                .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnVehiclesLayout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(returnVehiclesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 710, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReturnCalculate_jButton6))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(returnVehiclesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 682, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnVehiclesLayout.createSequentialGroup()
                        .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReturnCash_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReturnCreditCard_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(ReturnPay_jButton2, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(389, 389, 389))
        );

        returnVehiclesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ReturnCalculate_jButton6, ReturnCheckOverDue_jButton2, ReturnCheck_jButton2, ReturnPay_jButton2});

        returnVehiclesLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {ReturnCash_jTextField2, ReturnCreditCard_jTextField1});

        returnVehiclesLayout.setVerticalGroup(
            returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(returnVehiclesLayout.createSequentialGroup()
                .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnVehiclesLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReturnVin_jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReturnCustomerPnobeNum_jLabel9)
                            .addComponent(ReturnCheck_jButton2))
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnVehiclesLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnVehiclesLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(ReturnDate_jLabel19))
                    .addComponent(ReturnDate_jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReturnCalculate_jButton6))
                .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(returnVehiclesLayout.createSequentialGroup()
                        .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(returnVehiclesLayout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ReturnTime_jLabel20)
                                    .addComponent(ReturnTimeHH_jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel21)
                                    .addComponent(ReturnTimeMM_jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel16))
                                .addGap(24, 24, 24)
                                .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(ReturnOdoRead_jLabel23)
                                    .addComponent(ReturnOdometer_jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel24))
                                .addGap(18, 18, 18)
                                .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(ReturnFuelReading_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(ReturnRoadStar_jCheckBox2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(ReturnRedeem_jCheckBox1)
                                .addGap(40, 40, 40)
                                .addComponent(ReturnCheckOverDue_jButton2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnVehiclesLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, returnVehiclesLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(ReturnCreditCard_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(38, 38, 38)
                        .addGroup(returnVehiclesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(ReturnCash_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(ReturnPay_jButton2)
                        .addGap(49, 49, 49))))
        );

        moduletab.addTab("Return", returnVehicles);

        manageCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Customer"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setText("First Name*       :");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        jPanel1.add(cusFristNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 100, -1));

        jLabel27.setText("Last Name*    :");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));
        jPanel1.add(cusLastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 110, -1));
        jPanel1.add(streetAddField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 230, -1));

        jLabel28.setText("Street Address* :");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel30.setText("Province*           :");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel31.setText("City*   :");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jLabel32.setText("Zip Code*   :");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 130, -1));

        jLabel33.setText("Phone No*         :");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 220, -1));

        jCheckBox3.setText("Club Member");
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jButton9.setText("Register");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        manageCustomer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1010, 350));

        moduletab.addTab("Manage Customer", manageCustomer);

        manageFleet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Add New Car"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setText("Car Type*       :");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 39, 100, -1));

        cartypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(cartypeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 180, -1));

        jLabel35.setText("Manufacturer*     :");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, -1));

        manufacturerCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(manufacturerCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 180, -1));

        jLabel36.setText("Name*      :");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        nameCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(nameCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, -1));

        addBtn.setText("Add");
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel2.add(addBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, -1, -1));

        jLabel15.setText("Branch*       :");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 160, -1, -1));

        branchCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(branchCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 180, -1));

        manageFleet.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 420, 280));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Remove Car"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setText("Remove");
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jLabel37.setText("Car Type*       :");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 180, -1));

        jLabel38.setText("Manufacturer*     :");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, -1));

        jLabel39.setText("Name *  :");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 180, -1));

        jLabel40.setText("Vehicle No*        :");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel4.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 180, -1));

        jLabel42.setText("CAD");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));
        jPanel4.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 60, -1));

        jLabel41.setText("Sale Price*          :");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        manageFleet.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 420, 280));

        moduletab.addTab("Manage Fleet", manageFleet);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1375, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 780, Short.MAX_VALUE)
        );

        moduletab.addTab("Reports", jPanel5);

        userNamepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstnameLbl.setText("First Name*   :");
        userNamepanel.add(firstnameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });
        userNamepanel.add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 210, -1));

        lastNameLbl.setText("Last Name*    :");
        userNamepanel.add(lastNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        userNamepanel.add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 210, -1));

        userNameLbl.setText("User Name*    :");
        userNamepanel.add(userNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
        userNamepanel.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 210, -1));

        emailIdLbl.setText("Email ID*        :");
        userNamepanel.add(emailIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        emailIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdFieldActionPerformed(evt);
            }
        });
        userNamepanel.add(emailIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 210, -1));

        passwordLbl.setText("Password*      :");
        userNamepanel.add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        userNamepanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 210, -1));

        roleGroupRadio.add(managerRadio);
        managerRadio.setText("Manager");
        managerRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerRadioActionPerformed(evt);
            }
        });
        userNamepanel.add(managerRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        roleGroupRadio.add(clerkRadio);
        clerkRadio.setText("Clerk");
        clerkRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clerkRadioActionPerformed(evt);
            }
        });
        userNamepanel.add(clerkRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        addEmployeeBtn.setText("Add Employee");
        addEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeBtnActionPerformed(evt);
            }
        });
        userNamepanel.add(addEmployeeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        branchIdCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        userNamepanel.add(branchIdCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 200, -1));

        branchIdLbl.setText("Branch ID*      :");
        userNamepanel.add(branchIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        roleLbl.setText("Role*            :");
        userNamepanel.add(roleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        moduletab.addTab("New Employee", userNamepanel);

        modulepane.add(moduletab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 810));
        moduletab.getAccessibleContext().setAccessibleName("Reservation");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginpanel, javax.swing.GroupLayout.DEFAULT_SIZE, 1392, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(modulepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(modulepane, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jLayeredPane1.setLayer(loginpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(modulepane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 810));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {

            ConnectDB.exeQuery("select * from Accounts");

            Encrypt en = new Encrypt();
            en.encryptPwd(pwdField);
            en.decryptPwd();

        try {
            while(ConnectDB.resultSet().next()){
                if( userField.getText().contains(ConnectDB.resultSet().getString("username")) && 
                        pwdField.getText().contains(ConnectDB.resultSet().getString("password"))){
                    System.out.println("Login success");
                    CommonFunc.username = userField.getText();//Yaoyao added ??
                    loginpanel.setVisible(false);
                    modulepane.setVisible(true);
                }else{
                   // System.out.println(ConnectDB.resultSet().getString("username"));
                    //System.out.println(ConnectDB.resultSet().getString("password"));
                }
                
            }   
        } catch (SQLException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        }
        ConnectDB.clearResultSet();
                } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        try {
            Rent rent = new Rent();
            Date pickupDate = CommonFunc.changeDateFormat(pickupDt);
            Date dropoffDate = CommonFunc.changeDateFormat(dropOffDate);
            String pickuptime = CommonFunc.sqlTime(pickupHour, pickupMin);
            String dropofftime = CommonFunc.sqlTime(dropoffHHSpin, dropoffMMSpin);
            String cat = vehicleCatCombo.getSelectedItem().toString();
            String type = vehicleTypeCombo.getSelectedItem().toString();
////            unreservedVehiTable.setModel(new javax.swing.table.DefaultTableModel(rent.getAvailableVehicles(cat, Integer.parseInt(brnchIdCombo.getSelectedItem().toString()), type),
////                    new String [] {
////                        "Vehicle ID", "Make", "Vehicle Type", "Colour", "Doors"
////                    }
////            ));     } catch (ClassNotFoundException ex) {
//            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
            unreservedVehiTable = new JTable(rent.getAvailableVehicles(cat, Integer.parseInt(brnchIdCombo.getSelectedItem().toString()), type));
        } catch (SQLException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        }
        jScrollPane1.setViewportView(unreservedVehiTable);
    }//GEN-LAST:event_searchBtnActionPerformed

    private void resetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetBtnActionPerformed
        cusNumField.setText("");
        dlNumField.setText("");
        ccNumField.setText("");
        expDateCh.cleanup();
        cardTypeCombo.setSelectedIndex(1);
        brnchIdCombo.setSelectedIndex(0);
        pickupDt.cleanup();
        pickupHour.setValue(0);
        pickupMin.setValue(0);
        dropOffDate.cleanup();
        dropoffHHSpin.setValue(0);
        dropoffMMSpin.setValue(0);
        unreservedVehiTable.removeAll();
        jScrollPane1.setViewportView(unreservedVehiTable);
        vehicleCatCombo.setSelectedItem("Select");
        
    }//GEN-LAST:event_resetBtnActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void emailIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdFieldActionPerformed

    private void managerRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerRadioActionPerformed
        if(managerRadio.isSelected()){
            role = managerRadio.getText();
        }
    }//GEN-LAST:event_managerRadioActionPerformed

    private void addEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeBtnActionPerformed
            Encrypt en = new Encrypt();
            String firstName = firstNameField.getText();
            String lastName = lastNameField.getText();
            String userName = userNameField.getText();
            String email = emailIdField.getText();
            String password = en.encryptPwd(passwordField);
            String branchId = branchIdCombo.getSelectedItem().toString();
            int countusers = 0;
            if(!firstName.isEmpty() && !lastName.isEmpty() && !userName.isEmpty() 
                    && !email.isEmpty() && !password.isEmpty() && !role.isEmpty() && !branchId.isEmpty()){
                try {
                    ConnectDB.exeQuery("SELECT COUNT(*) AS COUNT FROM USER WHERE USERNAME = '"+userName+"'");
                    while(ConnectDB.resultSet().next()){
                        System.out.println("**"+ConnectDB.resultSet().getString(1));
                        countusers = Integer.parseInt(ConnectDB.resultSet().getString("COUNT"));
                    }
                    System.out.println(role);
                    if(countusers==0){               
                        ConnectDB.exeUpdate("INSERT INTO `superrent`.`user` (`firstname`, `lastname`, `username`, `email`, `password`, `role`, `branch`, `location`) "
                            + "VALUES ('"+firstName+"', '"+lastName+"', '"+userName+"', '"+email+"', '"+password+"', '"+role+"', '"+branchId+"', 'Vancouver');");                    
                    }else{
                        JOptionPane.showMessageDialog(null, "This user name has been used already");
                    }
                    ConnectDB.clearResultSet();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Should enter all the mandatory fields (*)");
            } 
            
    }//GEN-LAST:event_addEmployeeBtnActionPerformed

    private void clerkRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clerkRadioActionPerformed
        if(clerkRadio.isSelected()){
            role = clerkRadio.getText();
        }
    }//GEN-LAST:event_clerkRadioActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void moduletabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moduletabMouseClicked

    }//GEN-LAST:event_moduletabMouseClicked

    private void brnchIdComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_brnchIdComboItemStateChanged
        vehicleCatCombo.removeAllItems();
       
        try {
            rt.fillVehicleCatCombo(vehicleCatCombo, brnchIdCombo, vehicleTypeCombo);

           
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        }
        clearEqupList(); 
    }//GEN-LAST:event_brnchIdComboItemStateChanged

    private void rentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rentBtnActionPerformed
        
        try {
            if(rt.validateCustomerInfo(cusNumField)>0){
                int cusID = rt.validateCustomerInfo(cusNumField);
                int brnchID = Integer.parseInt(brnchIdCombo.getSelectedItem().toString());
                String vehicleTyp = vehicleCatCombo.getSelectedItem().toString();
                Date pickupDate = CommonFunc.changeDateFormat(pickupDt);
                Date dropoffDate = CommonFunc.changeDateFormat(dropOffDate);
                String pickuptime = CommonFunc.sqlTime(pickupHour, pickupMin);
                String dropofftime = CommonFunc.sqlTime(dropoffHHSpin, dropoffMMSpin);
                long ReservationID = rt.genUniqueID();
                       
                
                if(pickupDate.before(new Date()) && (dropoffDate.after(pickupDate) || dropoffDate.equals(new Date()))){
                    JOptionPane.showMessageDialog(null, "Pickup date should be after or equal to current date \n Dropoff date should be equal to pickup date of after pickup date");
                    return;
                }else{
                    String dlNum = dlNumField.getText();

                    String ccNum = ccNumField.getText();
                    Date expDate = CommonFunc.changeDateFormat(expDateCh);
                    String cardType = cardTypeCombo.getSelectedItem().toString();
                   
                    

                    int vehicleId =Integer.parseInt((String) unreservedVehiTable.getValueAt(unreservedVehiTable.getSelectedRow(), 0));
                    ConnectDB.exeUpdate("Update vehicles set isReturned = 0 where Vehicle_ID ="+vehicleId);
                    
                    ConnectDB.exeUpdate("INSERT INTO `superrent`.`reservation` (`ReservationID`, `CustomerID`, `BranchID`, `Vehicle_Type`, `Pickup_Date`, `Dropoff_Date`,  `Vehicle_ID`)"
                        + "VALUES ("+ReservationID+", "+cusID+", "+brnchID+", '"+vehicleTyp+"', '"+pickupDate+" "+pickuptime+"', '"+dropoffDate+" "+dropofftime+"', '"+vehicleId+"')");
                    
                    ConnectDB.exeUpdate("INSERT INTO `superrent`.`rental` (`ReservationID`, `DL_number`, `CCType`, `CC_Number`, `CC_ExpDate`) "
                            + "VALUES ("+ReservationID+", '"+dlNum+"', '"+cardType+"', "+ccNum+", '"+expDate+"');");                    
                    
                }               
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_rentBtnActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        try {
            // TODO add your handling code here:{
            String cartype = null;
            if(cartypeCombo.getSelectedItem()!= null){
                cartype = cartypeCombo.getSelectedItem().toString();
            }
            
            String manufacturer = null;
            if(manufacturerCombo.getSelectedItem()!= null){
                manufacturer = manufacturerCombo.getSelectedItem().toString();
            }
            
            String name = null;
            if(nameCombo.getSelectedItem()!=null){
                name = nameCombo.getSelectedItem().toString();
            }
            
            String branch = null;
            if(branchCombo.getSelectedItem()!=null){
                branch = branchCombo.getSelectedItem().toString();
                
            }
            int branchid = Integer.parseInt(branch);
            
            PreparedStatement ps = ConnectDB.exeUpdateprestatement("INSERT INTO vehicles (Vehicle_ID, Vehicle_Type, Branch_ID, Availability, Manufacturer, Name) VALUES (1119, ?,?,1,?,? )");
            ps.setString(1, cartype);
            ps.setInt(2,branchid);
            ps.setString(3,manufacturer);
            ps.setString(4,name);
            ps.executeUpdate();
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        }

    
    }//GEN-LAST:event_addBtnActionPerformed

    
    //private void initReserve() throws ClassNotFoundException, SQLException, IOException{


                                                    


    private void vehicleTypeComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vehicleTypeComboItemStateChanged
        if(!brnchIdCombo.getSelectedItem().toString().equals("Select")){
            vehicleCatCombo.removeAllItems();
            try {
                rt.fillVehicleCatCombo(vehicleCatCombo, brnchIdCombo, vehicleTypeCombo);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
            }           
        }
        clearEqupList(); 
    }//GEN-LAST:event_vehicleTypeComboItemStateChanged

    private void vehicleCatComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vehicleCatComboActionPerformed
        clearEqupList(); 
    }//GEN-LAST:event_vehicleCatComboActionPerformed
    
    private void clearEqupList(){
        equipSelected.clear();
        selectedList = new JList();
        equipmentsList = new JList();
        jScrollPane5.setViewportView(selectedList);
        jScrollPane4.setViewportView(equipmentsList);
    }
    private void searchEqupBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEqupBtnActionPerformed
        DefaultListModel ar = null;
        if(!brnchIdCombo.getSelectedItem().toString().equals("Select")){
            try {
                ar = rt.fillEquipmentList(equipmentsList, vehicleTypeCombo, brnchIdCombo);
            } catch (ClassNotFoundException ex) {
                Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
            } catch (InterruptedException ex) {
                Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
            }
            equipmentsList = new JList(ar);
            jScrollPane4.setViewportView(equipmentsList);
        }

    }//GEN-LAST:event_searchEqupBtnActionPerformed

    private void addEquipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEquipBtnActionPerformed
        if(equipmentsList.getSelectedValuesList().size()>0){    
            for(int i=0; i<equipmentsList.getSelectedValuesList().size(); i++){
                equipSelected.add(equipmentsList.getSelectedValuesList().get(i).toString());                
            }
            selectedList = new JList(equipSelected.toArray());
            jScrollPane5.setViewportView(selectedList);
        }
    }//GEN-LAST:event_addEquipBtnActionPerformed

    private void removeEquipBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEquipBtnActionPerformed
        if(selectedList.getSelectedValuesList().size()>0){
            equipSelected.remove(selectedList.getSelectedIndex());
            selectedList = new JList(equipSelected.toArray());
            jScrollPane5.setViewportView(selectedList);
        }
    }//GEN-LAST:event_removeEquipBtnActionPerformed

    private void ReturnVin_jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnVin_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnVin_jTextField8ActionPerformed

    private void ReturnRoadStar_jCheckBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnRoadStar_jCheckBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnRoadStar_jCheckBox2ActionPerformed

    private void ReturnCalculate_jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnCalculate_jButton6ActionPerformed
        // TODO add your handling code here:
        if(!ReturnVin_jTextField8.getText().isEmpty() && !ReturnOdoRead_jLabel23.getText().isEmpty() &&
            !ReturnFuelReading_jTextField2.getText().isEmpty()){
            String vin = ReturnVin_jTextField8.getText();
            String[] ResrTime = new String [2];
            String OdeReading = ReturnOdometer_jTextField9.getText();
            String FuelReading = ReturnFuelReading_jTextField2.getText();
            boolean RoadStar = ReturnRoadStar_jCheckBox2.isSelected();
            boolean Reedeem = ReturnRedeem_jCheckBox1.isSelected();
            try {
                Date dropoffDate = CommonFunc.changeDateFormat(ReturnDate_jDateChooser3);
                String dropofftime = CommonFunc.sqlTime(ReturnTimeHH_jSpinner1, ReturnTimeMM_jSpinner1);//? need minutes?
                //dropofftime
                ReturnDisplayFee_jTable2.setModel(new javax.swing.table.
                    DefaultTableModel(MyReturn.getCalculateFee(vin,RoadStar, FuelReading,OdeReading,Reedeem,dropoffDate),new String[]{
                        "Entry" , "Details","Cost"
                    }));
                    TableColumn firsetColumn = ReturnDisplayFee_jTable2.getColumnModel().getColumn(0);
                    firsetColumn.setMaxWidth(150);
                    firsetColumn.setMinWidth(150);
                    //            TableColumn SecColumn = ReturnDisplayFee_jTable2.getColumnModel().getColumn(1);
                    //            SecColumn.setMinWidth(200);
                    TableColumn ThirdColumn = ReturnDisplayFee_jTable2.getColumnModel().getColumn(2);
                    ThirdColumn.setMaxWidth(120);
                    ThirdColumn.setMinWidth(120);

                }catch (ParseException ex) {
                    Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Please input all necessary information.");
            }

    }//GEN-LAST:event_ReturnCalculate_jButton6ActionPerformed

    private void ReturnCheckOverDueDis_jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReturnCheckOverDueDis_jTable2MouseClicked
        // TODO add your handling code here:
        String Return_Date = ReturnDate_jDateChooser3.getDateFormatString();
        //System.out.println("The return date is" + Return_Date);
    }//GEN-LAST:event_ReturnCheckOverDueDis_jTable2MouseClicked

    private void ReturnCheck_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnCheck_jButton2ActionPerformed
        // TODO add your handling code here:

        String vin = ReturnVin_jTextField8.getText();
        if (!vin.isEmpty()){
            ReturnDisplay_jTable2.setModel(new javax.swing.table.DefaultTableModel (MyReturn.getResrInfo(vin),
                new String[]{
                    "Confirmation No" , "Customer ID", "Vin", "Status"
                }))
                ;

            }else{
                JOptionPane.showMessageDialog(null, "Please input the Vin.");
            }
    }//GEN-LAST:event_ReturnCheck_jButton2ActionPerformed

    private void ReturnFuelReading_jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnFuelReading_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnFuelReading_jTextField2ActionPerformed

    private void ReturnCheckOverDue_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnCheckOverDue_jButton2ActionPerformed
        // TODO add your handling code here:
        ReturnCheckOverDueDis_jTable2.setModel(new javax.swing.table.DefaultTableModel (MyReturn.getOverDue(),
            new String[]{
                "Confirmation No" , "Customer ID", "Phone No", "Branch ID", "Expected Time"
                ,"Vin"
            }));
    }//GEN-LAST:event_ReturnCheckOverDue_jButton2ActionPerformed

    private void ReturnRedeem_jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnRedeem_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnRedeem_jCheckBox1ActionPerformed

    private void ReturnPay_jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnPay_jButton2ActionPerformed
        // TODO add your handling code here:
        String vin = "";
        String[] ResrTime = new String[2];
        String OdeReading ="";
        String FuelReading = "";
        boolean RoadStar = false;
        boolean Reedeem = false;
        String[][] CalcuResult = new String[15][3];
         String username = "";
         String staff_id = "";
         String branch_id = "";
         String car_status = "";
         String confirmationID = "";
         String customeID = "";
         
            
        if(!ReturnVin_jTextField8.getText().isEmpty() && !ReturnOdoRead_jLabel23.getText().isEmpty() &&
            !ReturnFuelReading_jTextField2.getText().isEmpty()){
             vin = ReturnVin_jTextField8.getText();    
            OdeReading = ReturnOdometer_jTextField9.getText();
             FuelReading = ReturnFuelReading_jTextField2.getText();
             RoadStar = ReturnRoadStar_jCheckBox2.isSelected();
             Reedeem = ReturnRedeem_jCheckBox1.isSelected();
            try {
                String[][] ReserInfo = new String[1][4];
                ReserInfo=Return.getResrInfo(vin);
                car_status = ReserInfo[0][3];
                confirmationID = ReserInfo[0][0];
                customeID = ReserInfo[0][1];
                    
                Date dropoffDate = CommonFunc.changeDateFormat(ReturnDate_jDateChooser3);
//                dropofftime = CommonFunc.sqlTime(ReturnTimeHH_jSpinner1, ReturnTimeMM_jSpinner1);//? need minutes?
                //dropofftime
                CalcuResult = MyReturn.getCalculateFee(vin,RoadStar, FuelReading,OdeReading,Reedeem,dropoffDate);
                ReturnDisplayFee_jTable2.setModel(new javax.swing.table.
                    DefaultTableModel(CalcuResult,new String[]{
                        "Entry" , "Details","Cost"
                    }));
                    TableColumn firsetColumn = ReturnDisplayFee_jTable2.getColumnModel().getColumn(0);
                    firsetColumn.setMaxWidth(150);
                    firsetColumn.setMinWidth(150);
                    //            TableColumn SecColumn = ReturnDisplayFee_jTable2.getColumnModel().getColumn(1);
                    //            SecColumn.setMinWidth(200);
                    TableColumn ThirdColumn = ReturnDisplayFee_jTable2.getColumnModel().getColumn(2);
                    ThirdColumn.setMaxWidth(120);
                    ThirdColumn.setMinWidth(120);
       
                }catch (ParseException ex) {
                    Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Please input all returning information.");
            }
        
        //Update tables;
        if(!ReturnCash_jTextField2.getText().isEmpty() && !ReturnCreditCard_jTextField1.getText().isEmpty()){
            try {
                username = CommonFunc.username;
                staff_id = MyReturn.getStaffInfo(username)[0];
                branch_id = MyReturn.getStaffInfo(username)[1];
                
                
                //update reserve table.
                ConnectDB.exeUpdate("update reserve set status = 'returned' where vin = '"+vin+"' and status = 'rented' ");
                
                //update fleet table.
                ConnectDB.exeUpdate("update fleet set odometer = '"+ReturnOdometer_jTextField9.getText()+"' where vin = '"+vin+"'");
                
                //update payment table
               long paymentID =  Rent.genUniqueID();
               Date dropOffDate_upd = CommonFunc.changeDateFormat(ReturnDate_jDateChooser3);
               String dropOffTime = CommonFunc.sqlTime(ReturnTimeHH_jSpinner1, ReturnTimeMM_jSpinner1);
               
                ConnectDB.exeUpdate("insert into payment ( payment_id, customer_id, purpose, total, cash, credit, points,"
                        + " create_time, id, branch_id, staff_id) "
                        + "values ( "+paymentID+",'"+customeID+"','rent','"+CalcuResult[14][2]+"','"+ReturnCash_jTextField2.getText()+"','"+ReturnCreditCard_jTextField1.getText()+"',"
                        + "'"+Double.parseDouble(CalcuResult[14][2])/5+"','"+dropOffDate_upd+" "+dropOffTime+"','111','"+branch_id+"','"+staff_id+"')");
            
                //update dropoff table ???
                String[] FeeRate = new String[8];
                FeeRate = MyReturn.getFeeRate(vin);
                
                ConnectDB.exeUpdate("insert into dropoff (confirmation_no, passed_odometer, gas_rate, gas_not_filled_by_liter, road_star)"
                        + "values ('"+confirmationID+"','"+OdeReading+"','"+FeeRate[7]+"','"+FuelReading+"',"+RoadStar+")");
                
                //update 
                
                
            
            } catch (ClassNotFoundException | SQLException | IOException | ParseException ex) {
                Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
        }else{
            JOptionPane.showMessageDialog(null, "Please input the payment information. ");
        }
        
    }//GEN-LAST:event_ReturnPay_jButton2ActionPerformed

    private void ReturnCreditCard_jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnCreditCard_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReturnCreditCard_jTextField1ActionPerformed

    private void initRent() throws ClassNotFoundException, SQLException, IOException{

       
       rt.fillBranchIDCombo(brnchIdCombo);
       pickupHour.setValue(now.get(Calendar.HOUR_OF_DAY));
       pickupMin.setValue(now.get(Calendar.MINUTE));
       
    }
   
    private void initReturn() throws ClassNotFoundException, SQLException, IOException{
        ReturnTimeHH_jSpinner1.setValue(now.get(Calendar.HOUR_OF_DAY));
        ReturnTimeMM_jSpinner1.setValue(now.get(Calendar.MINUTE));
        ReturnDate_jDateChooser3.setDate(now.getTime()); 
        
    }

       private void initManageFleet() throws ClassNotFoundException, SQLException, IOException{
       cartypeCombo.removeAllItems();
       manufacturerCombo.removeAllItems();
       nameCombo.removeAllItems();
       branchCombo.removeAllItems();
       mf.fillCarType(cartypeCombo);  
       mf.fillManufacturer(manufacturerCombo);
       mf.fillName(nameCombo);
       mf.fillBranch(branchCombo);
    }

    /**
     * @param args the command line arguments
     */
    
    //private javax.swing.JPasswordField jTextField3;
    SpinnerModel modelPickHH = new SpinnerNumberModel(0, 0, 23 ,1);
    SpinnerModel modelPickMM = new SpinnerNumberModel(0, 0, 59 ,1);
    SpinnerModel modelDropHH = new SpinnerNumberModel(0, 0, 23 ,1);
    SpinnerModel modelDropMM = new SpinnerNumberModel(0, 0, 59 ,1);
    
    Calendar now = Calendar.getInstance();
    private Rent rt = new Rent();
    private String role;
    // Yaoyao added
    private Return MyReturn = new Return();
    private ArrayList<String> equipSelected = new ArrayList<String>();
    private ManageFleet mf = new ManageFleet();
    //private String role;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel RentVehicles;
    private javax.swing.JButton ReturnCalculate_jButton6;
    private javax.swing.JTextField ReturnCash_jTextField2;
    private javax.swing.JTable ReturnCheckOverDueDis_jTable2;
    private javax.swing.JButton ReturnCheckOverDue_jButton2;
    private javax.swing.JButton ReturnCheck_jButton2;
    private javax.swing.JTextField ReturnCreditCard_jTextField1;
    private javax.swing.JLabel ReturnCustomerPnobeNum_jLabel9;
    private com.toedter.calendar.JDateChooser ReturnDate_jDateChooser3;
    private javax.swing.JLabel ReturnDate_jLabel19;
    private javax.swing.JTable ReturnDisplayFee_jTable2;
    private javax.swing.JTable ReturnDisplay_jTable2;
    private javax.swing.JTextField ReturnFuelReading_jTextField2;
    private javax.swing.JLabel ReturnOdoRead_jLabel23;
    private javax.swing.JTextField ReturnOdometer_jTextField9;
    private javax.swing.JButton ReturnPay_jButton2;
    private javax.swing.JCheckBox ReturnRedeem_jCheckBox1;
    private javax.swing.JCheckBox ReturnRoadStar_jCheckBox2;
    private javax.swing.JSpinner ReturnTimeHH_jSpinner1;
    private javax.swing.JSpinner ReturnTimeMM_jSpinner1;
    private javax.swing.JLabel ReturnTime_jLabel20;
    private javax.swing.JTextField ReturnVin_jTextField8;
    private javax.swing.JButton addBtn;
    private javax.swing.JButton addEmployeeBtn;
    private javax.swing.JButton addEquipBtn;
    private javax.swing.JComboBox branchCombo;
    private javax.swing.JComboBox branchIdCombo;
    private javax.swing.JLabel branchIdLbl;
    private javax.swing.JComboBox brnchIdCombo;
    private javax.swing.JLabel brnchIdLbl;
    private javax.swing.JComboBox cardTypeCombo;
    private javax.swing.JLabel cardTypeLbl;
    private javax.swing.JComboBox cartypeCombo;
    private javax.swing.JTextField ccNumField;
    private javax.swing.JLabel ccNumLbl;
    private javax.swing.JRadioButton clerkRadio;
    private javax.swing.JTextField cusFristNameField;
    private javax.swing.JTextField cusLastNameField;
    private javax.swing.JTextField cusNumField;
    private javax.swing.JLabel cusNumLbl;
    private javax.swing.JTextField dlNumField;
    private javax.swing.JLabel dlNumLbl;
    private com.toedter.calendar.JDateChooser dropOffDate;
    private javax.swing.JSpinner dropoffHHSpin;
    private javax.swing.JSpinner dropoffMMSpin;
    private javax.swing.JTextField emailIdField;
    private javax.swing.JLabel emailIdLbl;
    private javax.swing.JList equipmentsList;
    private com.toedter.calendar.JDateChooser expDateCh;
    private javax.swing.JLabel expDateLbl;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstnameLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JPanel manageCustomer;
    private javax.swing.JPanel manageFleet;
    private javax.swing.JRadioButton managerRadio;
    private javax.swing.JComboBox manufacturerCombo;
    private javax.swing.JPanel modulepane;
    private javax.swing.JTabbedPane moduletab;
    private javax.swing.JComboBox nameCombo;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLbl;
    private com.toedter.calendar.JDateChooser pickupDt;
    private javax.swing.JSpinner pickupHour;
    private javax.swing.JSpinner pickupMin;
    private javax.swing.JTextField pwdField;
    private javax.swing.JButton removeEquipBtn;
    private javax.swing.JButton rentBtn;
    private javax.swing.JPanel reserveVehicles;
    private javax.swing.JButton resetBtn;
    private javax.swing.JPanel returnVehicles;
    private javax.swing.ButtonGroup roleGroupRadio;
    private javax.swing.JLabel roleLbl;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton searchEqupBtn;
    private javax.swing.JList selectedList;
    private javax.swing.JTextField streetAddField;
    private javax.swing.JTable unreservedVehiTable;
    private javax.swing.JTextField userField;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JPanel userNamepanel;
    private javax.swing.JComboBox vehicleCatCombo;
    private javax.swing.JComboBox vehicleTypeCombo;
    // End of variables declaration//GEN-END:variables
}
