/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.superrent.gui;

import com.superrent.DataBase.ConnectDB;
import com.superrent.modules.Encrypt;
import com.superrent.modules.CommonFunc;
import com.superrent.modules.Rent;
import java.io.IOException;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Iniyan
 */
public class SuperRent extends javax.swing.JFrame {

    /**
     * Creates new form SuperRent
     */
    public SuperRent() throws ClassNotFoundException, SQLException, IOException {
        initComponents();
        initRent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleGroupRadio = new javax.swing.ButtonGroup();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        loginpanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        userField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        pwdField = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        jButton12 = new javax.swing.JButton();
        modulepane = new javax.swing.JPanel();
        moduletab = new javax.swing.JTabbedPane();
        Reserve = new javax.swing.JPanel();
        jLabel49 = new javax.swing.JLabel();
        ReserveBranchLocation_ComboBox = new javax.swing.JComboBox();
        ReserveRentDate_DateChooser = new com.toedter.calendar.JDateChooser();
        jLabel50 = new javax.swing.JLabel();
        ReserveRentTimeHour_Spinner3 = new javax.swing.JSpinner();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        ReserveRentTimeMinutes_Spinner4 = new javax.swing.JSpinner();
        jLabel53 = new javax.swing.JLabel();
        ReserveCarType_jComboBox = new javax.swing.JComboBox();
        jLabel54 = new javax.swing.JLabel();
        ReserveTruckType_ComboBox = new javax.swing.JComboBox();
        jLabel55 = new javax.swing.JLabel();
        ReserveFeatures_ComboBox = new javax.swing.JComboBox();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        ReserveSearch_jButton = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jLabel56 = new javax.swing.JLabel();
        jLabel57 = new javax.swing.JLabel();
        ReserveCustomerPhoneNum_TextField = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        ReserveConfirmNumber_TextField = new javax.swing.JTextField();
        jLabel59 = new javax.swing.JLabel();
        ReserveDriverLicense_TextField = new javax.swing.JTextField();
        returnVehicles = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();
        jLabel20 = new javax.swing.JLabel();
        jSpinField1 = new com.toedter.components.JSpinField();
        jSpinField2 = new com.toedter.components.JSpinField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jButton6 = new javax.swing.JButton();
        jTextField10 = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        rentVehicles = new javax.swing.JPanel();
        brnchIdLbl = new javax.swing.JLabel();
        brnchIdCombo = new javax.swing.JComboBox();
        pickupDt = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        pickupHour = new javax.swing.JSpinner(modelPickHH);
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        pickupMin = new javax.swing.JSpinner(modelPickMM);
        jLabel8 = new javax.swing.JLabel();
        vehicleTypeCombo = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox();
        jLabel11 = new javax.swing.JLabel();
        equipmentsCombo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        cusNumLbl = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cusNumField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        dlNumLbl = new javax.swing.JLabel();
        dlNumField = new javax.swing.JTextField();
        ccNumLbl = new javax.swing.JLabel();
        ccNumField = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        expDateLbl = new javax.swing.JLabel();
        expDateCh = new com.toedter.calendar.JDateChooser();
        cardTypeLbl = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        dropOffDate = new com.toedter.calendar.JDateChooser();
        jLabel44 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        cardTypeCombo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        dropoffHHSpin = new javax.swing.JSpinner(modelDropHH);
        jSpinner2 = new javax.swing.JSpinner(modelDropMM);
        manageCustomer = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        cusFristNameField = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        cusLastNameField = new javax.swing.JTextField();
        streetAddField = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox();
        jComboBox6 = new javax.swing.JComboBox();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jTextField16 = new javax.swing.JTextField();
        jCheckBox3 = new javax.swing.JCheckBox();
        jButton9 = new javax.swing.JButton();
        manageFleet = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel34 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jLabel35 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        jComboBox9 = new javax.swing.JComboBox();
        jButton10 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton11 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        jComboBox10 = new javax.swing.JComboBox();
        jLabel38 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox();
        jLabel39 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox();
        jLabel40 = new javax.swing.JLabel();
        jTextField17 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField18 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        userNamepanel = new javax.swing.JPanel();
        firstnameLbl = new javax.swing.JLabel();
        firstNameField = new javax.swing.JTextField();
        lastNameLbl = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        userNameLbl = new javax.swing.JLabel();
        userNameField = new javax.swing.JTextField();
        emailIdLbl = new javax.swing.JLabel();
        emailIdField = new javax.swing.JTextField();
        passwordLbl = new javax.swing.JLabel();
        passwordField = new javax.swing.JPasswordField();
        managerRadio = new javax.swing.JRadioButton();
        clerkRadio = new javax.swing.JRadioButton();
        addEmployeeBtn = new javax.swing.JButton();
        branchIdCombo = new javax.swing.JComboBox();
        branchIdLbl = new javax.swing.JLabel();
        roleLbl = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        loginpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("User Name :");
        loginpanel.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 270, -1, -1));
        loginpanel.add(userField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 270, 220, -1));

        jLabel2.setText("Password   :");
        loginpanel.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 320, -1, -1));
        loginpanel.add(pwdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 320, 220, -1));

        jButton1.setText("Employee Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        loginpanel.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 370, 160, -1));
        loginpanel.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, 340, 10));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jLabel4.setText("Super Rent Login Page");
        loginpanel.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 70, 440, 70));

        jButton12.setText("Change Password");
        loginpanel.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, -1, -1));

        modulepane.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        moduletab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moduletabMouseClicked(evt);
            }
        });

        jLabel49.setText("Branch Location* :");

        ReserveBranchLocation_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        ReserveBranchLocation_ComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserveBranchLocation_ComboBoxActionPerformed(evt);
            }
        });

        jLabel50.setText("Rent Date* :");

        jLabel51.setText("Rent Time :");

        jLabel52.setText("HH");

        jLabel53.setText("MM");

        ReserveCarType_jComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel54.setText("Truck Type*  :");

        ReserveTruckType_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel55.setText("Features* :");

        ReserveFeatures_ComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        ReserveSearch_jButton.setText("Search");
        ReserveSearch_jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserveSearch_jButtonActionPerformed(evt);
            }
        });

        jButton14.setText("Reset");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setText("Rent");

        jLabel56.setText("Customer Phone Number* :");

        jLabel57.setText("Car Type* :");

        jLabel58.setText("Confirmation Number :");

        ReserveConfirmNumber_TextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReserveConfirmNumber_TextFieldActionPerformed(evt);
            }
        });

        jLabel59.setText("Driver License*  :");

        javax.swing.GroupLayout ReserveLayout = new javax.swing.GroupLayout(Reserve);
        Reserve.setLayout(ReserveLayout);
        ReserveLayout.setHorizontalGroup(
            ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReserveLayout.createSequentialGroup()
                .addGroup(ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ReserveLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addGroup(ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel57, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel55, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel50, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel56, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel58, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReserveConfirmNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReserveCustomerPhoneNum_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReserveBranchLocation_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReserveRentDate_DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReserveCarType_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReserveFeatures_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel54, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel59, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(3, 3, 3)
                        .addGroup(ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ReserveDriverLicense_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ReserveTruckType_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(ReserveLayout.createSequentialGroup()
                        .addGap(370, 370, 370)
                        .addComponent(ReserveSearch_jButton)
                        .addGap(55, 55, 55)
                        .addComponent(jButton14))
                    .addGroup(ReserveLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 840, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ReserveLayout.createSequentialGroup()
                        .addGap(450, 450, 450)
                        .addComponent(jButton15))
                    .addGroup(ReserveLayout.createSequentialGroup()
                        .addGap(602, 602, 602)
                        .addGroup(ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel51)
                            .addGroup(ReserveLayout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(ReserveRentTimeHour_Spinner3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(10, 10, 10)
                        .addComponent(jLabel52)
                        .addGap(0, 0, 0)
                        .addComponent(ReserveRentTimeMinutes_Spinner4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel53)))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        ReserveLayout.setVerticalGroup(
            ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ReserveLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel58, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ReserveConfirmNumber_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel56)
                    .addComponent(ReserveCustomerPhoneNum_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel59)
                    .addComponent(ReserveDriverLicense_TextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel49)
                    .addComponent(ReserveBranchLocation_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel50)
                    .addComponent(ReserveRentDate_DateChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel51)
                    .addComponent(ReserveRentTimeHour_Spinner3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel52)
                    .addComponent(ReserveRentTimeMinutes_Spinner4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53))
                .addGap(22, 22, 22)
                .addGroup(ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel57)
                    .addComponent(ReserveCarType_jComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel54)
                    .addComponent(ReserveTruckType_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel55)
                    .addComponent(ReserveFeatures_ComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(ReserveLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ReserveSearch_jButton)
                    .addComponent(jButton14))
                .addGap(11, 11, 11)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jButton15))
        );

        moduletab.addTab("Reserve", Reserve);

        returnVehicles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setText("Customer Phone Number*   :");
        returnVehicles.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 56, -1, -1));
        returnVehicles.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 180, -1));

        jLabel19.setText("Return Date*                     :");
        returnVehicles.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, -1, -1));
        returnVehicles.add(jDateChooser3, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, 180, -1));

        jLabel20.setText("Return Time*                    :");
        returnVehicles.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, -1, -1));
        returnVehicles.add(jSpinField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 50, -1));
        returnVehicles.add(jSpinField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 150, 40, -1));

        jLabel21.setText("HH");
        returnVehicles.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, -1, -1));

        jLabel22.setText("MM");
        returnVehicles.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));

        jLabel23.setText("Current Odometer Reading*:");
        returnVehicles.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, -1, -1));
        returnVehicles.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 200, 70, -1));

        jLabel24.setText("Miles");
        returnVehicles.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jCheckBox1.setText("Fuel Check");
        returnVehicles.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, -1, -1));

        jCheckBox2.setText("Road Star");
        returnVehicles.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, -1, -1));

        jButton6.setText("Calculate");
        returnVehicles.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 350, -1, -1));
        returnVehicles.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 350, 90, -1));

        jLabel25.setText("CAD");
        returnVehicles.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, -1, -1));

        jButton7.setText("Pay");
        returnVehicles.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 420, -1, -1));

        jButton8.setText("Redeem");
        returnVehicles.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, -1, -1));

        moduletab.addTab("Return", returnVehicles);

        rentVehicles.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        brnchIdLbl.setText("Branch ID*                       :");
        rentVehicles.add(brnchIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        brnchIdCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "select" }));
        brnchIdCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                brnchIdComboItemStateChanged(evt);
            }
        });
        brnchIdCombo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                brnchIdComboMouseClicked(evt);
            }
        });
        brnchIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brnchIdComboActionPerformed(evt);
            }
        });
        rentVehicles.add(brnchIdCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 190, 370, -1));
        rentVehicles.add(pickupDt, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 230, 140, -1));

        jLabel3.setText("Pickup Date*                    :");
        rentVehicles.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));
        rentVehicles.add(pickupHour, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 230, 40, -1));

        jLabel6.setText("Pickup Time :");
        rentVehicles.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 230, -1, -1));

        jLabel7.setText("HH");
        rentVehicles.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));
        rentVehicles.add(pickupMin, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 40, -1));

        jLabel8.setText("MM");
        rentVehicles.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, -1, -1));

        vehicleTypeCombo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                vehicleTypeComboItemStateChanged(evt);
            }
        });
        rentVehicles.add(vehicleTypeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 310, 220, -1));

        jLabel10.setText("Track Type*  :");
        rentVehicles.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 310, -1, -1));

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        rentVehicles.add(jComboBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, 220, -1));

        jLabel11.setText("Equipments*                    :");
        rentVehicles.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, -1, -1));

        equipmentsCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "None" }));
        equipmentsCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentsComboActionPerformed(evt);
            }
        });
        rentVehicles.add(equipmentsCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 350, 220, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Vehicle ID", "Make", "Vehicle Type", "Colour", "Doors"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        rentVehicles.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 840, 130));

        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        rentVehicles.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 400, -1, -1));

        jButton3.setText("Reset");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        rentVehicles.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 400, -1, -1));

        jButton4.setText("Rent");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        rentVehicles.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 590, -1, -1));

        cusNumLbl.setText("Customer Phone Number* :");
        rentVehicles.add(cusNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));

        jLabel13.setText("Vehicle Type*                  :");
        rentVehicles.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, -1));
        rentVehicles.add(cusNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 130, -1));

        jLabel14.setText("Confirmation Number         :");
        rentVehicles.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));
        rentVehicles.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 50, 130, -1));

        dlNumLbl.setText("Driver License*  :");
        rentVehicles.add(dlNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 100, -1, -1));
        rentVehicles.add(dlNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 160, -1));

        ccNumLbl.setText("Credit Card Number*        :");
        rentVehicles.add(ccNumLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        rentVehicles.add(ccNumField, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 150, 130, -1));

        jButton5.setText("Auto Fill");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        rentVehicles.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 130, -1));

        expDateLbl.setText("Expiry Date*      :");
        rentVehicles.add(expDateLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 150, -1, -1));
        rentVehicles.add(expDateCh, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 160, -1));

        cardTypeLbl.setText("Card type*  :");
        rentVehicles.add(cardTypeLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        jLabel43.setText("Dropoff*                          :");
        rentVehicles.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));
        rentVehicles.add(dropOffDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 270, 140, -1));

        jLabel44.setText("Dropoff Time :");
        rentVehicles.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 270, -1, -1));

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        rentVehicles.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 380, 110, -1));

        cardTypeCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "American Express", "MasterCard", "Visa" }));
        rentVehicles.add(cardTypeCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 150, -1));

        jLabel5.setText("HH");
        rentVehicles.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 270, -1, -1));

        jLabel12.setText("MM");
        rentVehicles.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, -1, -1));
        rentVehicles.add(dropoffHHSpin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 40, -1));
        rentVehicles.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 270, 40, -1));

        moduletab.addTab("Rent", rentVehicles);

        manageCustomer.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Add Customer"));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setText("First Name*       :");
        jPanel1.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        jPanel1.add(cusFristNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 40, 100, -1));

        jLabel27.setText("Last Name*    :");
        jPanel1.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));
        jPanel1.add(cusLastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 40, 110, -1));
        jPanel1.add(streetAddField, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 90, 230, -1));

        jLabel28.setText("Street Address* :");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jLabel30.setText("Province*           :");
        jPanel1.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 110, -1));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 140, 150, -1));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, -1));

        jLabel31.setText("City*   :");
        jPanel1.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 140, -1, -1));

        jLabel32.setText("Zip Code*   :");
        jPanel1.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 140, -1, -1));
        jPanel1.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 140, 130, -1));

        jLabel33.setText("Phone No*         :");
        jPanel1.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, -1, -1));
        jPanel1.add(jTextField16, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 220, -1));

        jCheckBox3.setText("Club Member");
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, -1, -1));

        jButton9.setText("Register");
        jPanel1.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, -1, -1));

        manageCustomer.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 1010, 350));

        moduletab.addTab("Manage Customer", manageCustomer);

        manageFleet.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Add New Car"));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel34.setText("Car Type*       :");
        jPanel2.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(36, 39, 100, -1));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 40, 180, -1));

        jLabel35.setText("Manufacturer*     :");
        jPanel2.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 120, -1));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 180, -1));

        jLabel36.setText("Name*      :");
        jPanel2.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(jComboBox9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, -1));

        jButton10.setText("Add");
        jPanel2.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, -1, -1));

        manageFleet.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 500, 220));

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Remove Car"));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton11.setText("Remove");
        jPanel4.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        jLabel37.setText("Car Type*       :");
        jPanel4.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox10, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 180, -1));

        jLabel38.setText("Manufacturer*     :");
        jPanel4.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox11, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 70, 180, -1));

        jLabel39.setText("Name *  :");
        jPanel4.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel4.add(jComboBox12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 110, 180, -1));

        jLabel40.setText("Vehicle No*        :");
        jPanel4.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));
        jPanel4.add(jTextField17, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 150, 180, -1));

        jLabel42.setText("CAD");
        jPanel4.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, -1, -1));
        jPanel4.add(jTextField18, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 190, 60, -1));

        jLabel41.setText("Sale Price*          :");
        jPanel4.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        manageFleet.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 510, 280));

        moduletab.addTab("Manage Fleet", manageFleet);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1085, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 630, Short.MAX_VALUE)
        );

        moduletab.addTab("Reports", jPanel5);

        userNamepanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        firstnameLbl.setText("First Name*   :");
        userNamepanel.add(firstnameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, -1, -1));

        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });
        userNamepanel.add(firstNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 210, -1));

        lastNameLbl.setText("Last Name*    :");
        userNamepanel.add(lastNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));
        userNamepanel.add(lastNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 210, -1));

        userNameLbl.setText("User Name*    :");
        userNamepanel.add(userNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));
        userNamepanel.add(userNameField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, 210, -1));

        emailIdLbl.setText("Email ID*        :");
        userNamepanel.add(emailIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, -1, -1));

        emailIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailIdFieldActionPerformed(evt);
            }
        });
        userNamepanel.add(emailIdField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 210, -1));

        passwordLbl.setText("Password*      :");
        userNamepanel.add(passwordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 280, -1, -1));
        userNamepanel.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, 210, -1));

        roleGroupRadio.add(managerRadio);
        managerRadio.setText("Manager");
        managerRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                managerRadioActionPerformed(evt);
            }
        });
        userNamepanel.add(managerRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 390, -1, -1));

        roleGroupRadio.add(clerkRadio);
        clerkRadio.setText("Clerk");
        clerkRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clerkRadioActionPerformed(evt);
            }
        });
        userNamepanel.add(clerkRadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, -1, -1));

        addEmployeeBtn.setText("Add Employee");
        addEmployeeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addEmployeeBtnActionPerformed(evt);
            }
        });
        userNamepanel.add(addEmployeeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, -1, -1));

        branchIdCombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        userNamepanel.add(branchIdCombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 200, -1));

        branchIdLbl.setText("Branch ID*      :");
        userNamepanel.add(branchIdLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, -1, -1));

        roleLbl.setText("Role*            :");
        userNamepanel.add(roleLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        moduletab.addTab("New Employee", userNamepanel);

        modulepane.add(moduletab, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1090, 660));
        moduletab.getAccessibleContext().setAccessibleName("Reservation");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(modulepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(loginpanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                    .addComponent(modulepane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jLayeredPane1.setLayer(loginpanel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(modulepane, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1380, 810));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            ConnectDB.exeQuery("Select * from user");
            Encrypt en = new Encrypt();
            en.encryptPwd(pwdField);
            en.decryptPwd();

        try {
            while(ConnectDB.resultSet().next()){
                if( userField.getText().contains(ConnectDB.resultSet().getString("username")) && 
                        pwdField.getText().contains(ConnectDB.resultSet().getString("password"))){
                    System.out.println("Login success");
                    loginpanel.setVisible(false);
                    modulepane.setVisible(true);
                }else{
                   // System.out.println(ConnectDB.resultSet().getString("username"));
                    //System.out.println(ConnectDB.resultSet().getString("password"));
                }
                
            }   } catch (SQLException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        }
        ConnectDB.clearResultSet();
                } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            jTable1.setModel(new javax.swing.table.DefaultTableModel(rt.getAvailableVehicles(vehicleTypeCombo.getSelectedItem().toString(), Integer.parseInt(brnchIdCombo.getSelectedItem().toString())),
                    new String [] {
                        "Vehicle ID", "Make", "Vehicle Type", "Colour", "Doors"
                    }
            ));     } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        }
        jScrollPane1.setViewportView(jTable1);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void emailIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailIdFieldActionPerformed

    private void managerRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_managerRadioActionPerformed
        if(managerRadio.isSelected()){
            role = managerRadio.getText();
        }
    }//GEN-LAST:event_managerRadioActionPerformed

    private void addEmployeeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addEmployeeBtnActionPerformed
            Encrypt en = new Encrypt();
            String firstName = firstNameField.getText();
            String lastName = lastNameField.getText();
            String userName = userNameField.getText();
            String email = emailIdField.getText();
            String password = en.encryptPwd(passwordField);
            String branchId = branchIdCombo.getSelectedItem().toString();
            int countusers = 0;
            if(!firstName.isEmpty() && !lastName.isEmpty() && !userName.isEmpty() 
                    && !email.isEmpty() && !password.isEmpty() && !role.isEmpty() && !branchId.isEmpty()){
                try {
                    ConnectDB.exeQuery("SELECT COUNT(*) AS COUNT FROM USER WHERE USERNAME = '"+userName+"'");
                    while(ConnectDB.resultSet().next()){
                        System.out.println("**"+ConnectDB.resultSet().getString(1));
                        countusers = Integer.parseInt(ConnectDB.resultSet().getString("COUNT"));
                    }
                    System.out.println(role);
                    if(countusers==0){               
                        ConnectDB.exeUpdate("INSERT INTO `superrent`.`user` (`firstname`, `lastname`, `username`, `email`, `password`, `role`, `branch`, `location`) "
                            + "VALUES ('"+firstName+"', '"+lastName+"', '"+userName+"', '"+email+"', '"+password+"', '"+role+"', '"+branchId+"', 'Vancouver');");                    
                    }else{
                        JOptionPane.showMessageDialog(null, "This user name has been used already");
                    }
                    ConnectDB.clearResultSet();
                } catch (ClassNotFoundException ex) {
                    Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
                } catch (SQLException ex) {
                    Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Should enter all the mandatory fields (*)");
            } 
            
    }//GEN-LAST:event_addEmployeeBtnActionPerformed

    private void clerkRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clerkRadioActionPerformed
        if(clerkRadio.isSelected()){
            role = clerkRadio.getText();
        }
    }//GEN-LAST:event_clerkRadioActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

    }//GEN-LAST:event_jButton5ActionPerformed

    private void moduletabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moduletabMouseClicked

    }//GEN-LAST:event_moduletabMouseClicked

    private void brnchIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brnchIdComboActionPerformed

    }//GEN-LAST:event_brnchIdComboActionPerformed

    private void brnchIdComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_brnchIdComboItemStateChanged
        vehicleTypeCombo.removeAllItems();
        equipmentsCombo.removeAllItems();
        try {
            rt.fillCarTypeCombo(vehicleTypeCombo, brnchIdCombo);
            rt.fillEquipmentCombo(equipmentsCombo, vehicleTypeCombo);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_brnchIdComboItemStateChanged

    private void brnchIdComboMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_brnchIdComboMouseClicked

    }//GEN-LAST:event_brnchIdComboMouseClicked

    private void vehicleTypeComboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_vehicleTypeComboItemStateChanged
        
        
    }//GEN-LAST:event_vehicleTypeComboItemStateChanged

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        try {
            if(rt.validateCustomerInfo(cusNumField)>0){
                int cusID = rt.validateCustomerInfo(cusNumField);
                int brnchID = Integer.parseInt(brnchIdCombo.getSelectedItem().toString());
                String vehicleTyp = vehicleTypeCombo.getSelectedItem().toString();
                Date pickupDate = CommonFunc.changeDateFormat(pickupDt);
                Date dropoffDate = CommonFunc.changeDateFormat(dropOffDate);
                String pickuptime = CommonFunc.sqlTime(pickupHour, pickupMin);
                String dropofftime = CommonFunc.sqlTime(dropoffHHSpin, jSpinner2);
                long ReservationID = rt.genUniqueID();
                       
                
                if(pickupDate.before(new Date()) && (dropoffDate.after(pickupDate) || dropoffDate.equals(new Date()))){
                    JOptionPane.showMessageDialog(null, "Pickup date should be after or equal to current date \n Dropoff date should be equal to pickup date of after pickup date");
                    return;
                }else{
                    String dlNum = dlNumField.getText();

                    String ccNum = ccNumField.getText();
                    Date expDate = CommonFunc.changeDateFormat(expDateCh);
                    String cardType = cardTypeCombo.getSelectedItem().toString();
                   
                    ConnectDB.exeUpdate("INSERT INTO `superrent`.`reservation` (`ReservationID`, `CustomerID`, `BranchID`, `Vehicle_Type`, `Pickup_Date`, `Pickup_Time`, `Dropoff_Date`, `Dropoff_time`)"
                        + "VALUES ("+ReservationID+", "+cusID+", "+brnchID+", '"+vehicleTyp+"', '"+pickupDate+"', '"+pickuptime+"', '"+dropoffDate+"', '"+dropofftime+"')");
                    
                    ConnectDB.exeUpdate("INSERT INTO `superrent`.`rental` (`ReservationID`, `DL_number`, `CCType`, `CC_Number`, `CC_ExpDate`) "
                            + "VALUES ("+ReservationID+", '"+dlNum+"', '"+cardType+"', "+ccNum+", '"+expDate+"');");
                    int vehicleId =Integer.parseInt((String) jTable1.getValueAt(jTable1.getSelectedRow(), 0));
                    ConnectDB.exeUpdate("Update vehicles set Availability = 0 where Vehicle_ID ="+vehicleId);
                }               
                
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(SuperRent.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void ReserveBranchLocation_ComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveBranchLocation_ComboBoxActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_ReserveBranchLocation_ComboBoxActionPerformed

    private void ReserveSearch_jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveSearch_jButtonActionPerformed
        // TODO add your handling code here:
        String confirNum = ReserveConfirmNumber_TextField.getText();
        String PhoneNum = ReserveCustomerPhoneNum_TextField.getText();
        String DriverLicen = ReserveDriverLicense_TextField.getText();
        String BranchLocation = ReserveBranchLocation_ComboBox.getName();

    }//GEN-LAST:event_ReserveSearch_jButtonActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton14ActionPerformed

    private void ReserveConfirmNumber_TextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReserveConfirmNumber_TextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ReserveConfirmNumber_TextFieldActionPerformed

    private void equipmentsComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentsComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentsComboActionPerformed
    
    private void initRent() throws ClassNotFoundException, SQLException, IOException{
       
       rt.fillBranchIDCombo(brnchIdCombo);
       pickupHour.setValue(now.get(Calendar.HOUR_OF_DAY));
       pickupMin.setValue(now.get(Calendar.MINUTE));
       
    }
    /**
     * @param args the command line arguments
     */
    
    //private javax.swing.JPasswordField jTextField3;
    SpinnerModel modelPickHH = new SpinnerNumberModel(0, 0, 23 ,1);
    SpinnerModel modelPickMM = new SpinnerNumberModel(0, 0, 59 ,1);
    SpinnerModel modelDropHH = new SpinnerNumberModel(0, 0, 23 ,1);
    SpinnerModel modelDropMM = new SpinnerNumberModel(0, 0, 59 ,1);
    Calendar now = Calendar.getInstance();
    private Rent rt = new Rent();
    private String role;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Reserve;
    private javax.swing.JComboBox ReserveBranchLocation_ComboBox;
    private javax.swing.JComboBox ReserveCarType_jComboBox;
    private javax.swing.JTextField ReserveConfirmNumber_TextField;
    private javax.swing.JTextField ReserveCustomerPhoneNum_TextField;
    private javax.swing.JTextField ReserveDriverLicense_TextField;
    private javax.swing.JComboBox ReserveFeatures_ComboBox;
    private com.toedter.calendar.JDateChooser ReserveRentDate_DateChooser;
    private javax.swing.JSpinner ReserveRentTimeHour_Spinner3;
    private javax.swing.JSpinner ReserveRentTimeMinutes_Spinner4;
    private javax.swing.JButton ReserveSearch_jButton;
    private javax.swing.JComboBox ReserveTruckType_ComboBox;
    private javax.swing.JButton addEmployeeBtn;
    private javax.swing.JComboBox branchIdCombo;
    private javax.swing.JLabel branchIdLbl;
    private javax.swing.JComboBox brnchIdCombo;
    private javax.swing.JLabel brnchIdLbl;
    private javax.swing.JComboBox cardTypeCombo;
    private javax.swing.JLabel cardTypeLbl;
    private javax.swing.JTextField ccNumField;
    private javax.swing.JLabel ccNumLbl;
    private javax.swing.JRadioButton clerkRadio;
    private javax.swing.JTextField cusFristNameField;
    private javax.swing.JTextField cusLastNameField;
    private javax.swing.JTextField cusNumField;
    private javax.swing.JLabel cusNumLbl;
    private javax.swing.JTextField dlNumField;
    private javax.swing.JLabel dlNumLbl;
    private com.toedter.calendar.JDateChooser dropOffDate;
    private javax.swing.JSpinner dropoffHHSpin;
    private javax.swing.JTextField emailIdField;
    private javax.swing.JLabel emailIdLbl;
    private javax.swing.JComboBox equipmentsCombo;
    private com.toedter.calendar.JDateChooser expDateCh;
    private javax.swing.JLabel expDateLbl;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel firstnameLbl;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox jComboBox10;
    private javax.swing.JComboBox jComboBox11;
    private javax.swing.JComboBox jComboBox12;
    private javax.swing.JComboBox jComboBox3;
    private javax.swing.JComboBox jComboBox5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboBox8;
    private javax.swing.JComboBox jComboBox9;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel55;
    private javax.swing.JLabel jLabel56;
    private javax.swing.JLabel jLabel57;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JLabel jLabel59;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator1;
    private com.toedter.components.JSpinField jSpinField1;
    private com.toedter.components.JSpinField jSpinField2;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField16;
    private javax.swing.JTextField jTextField17;
    private javax.swing.JTextField jTextField18;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JLabel lastNameLbl;
    private javax.swing.JPanel loginpanel;
    private javax.swing.JPanel manageCustomer;
    private javax.swing.JPanel manageFleet;
    private javax.swing.JRadioButton managerRadio;
    private javax.swing.JPanel modulepane;
    private javax.swing.JTabbedPane moduletab;
    private javax.swing.JTextField passwordField;
    private javax.swing.JLabel passwordLbl;
    private com.toedter.calendar.JDateChooser pickupDt;
    private javax.swing.JSpinner pickupHour;
    private javax.swing.JSpinner pickupMin;
    private javax.swing.JTextField pwdField;
    private javax.swing.JPanel rentVehicles;
    private javax.swing.JPanel returnVehicles;
    private javax.swing.ButtonGroup roleGroupRadio;
    private javax.swing.JLabel roleLbl;
    private javax.swing.JTextField streetAddField;
    private javax.swing.JTextField userField;
    private javax.swing.JTextField userNameField;
    private javax.swing.JLabel userNameLbl;
    private javax.swing.JPanel userNamepanel;
    private javax.swing.JComboBox vehicleTypeCombo;
    // End of variables declaration//GEN-END:variables
}
